- name: Get current container id
  shell: cat /proc/self/cgroup | grep -o  -e "docker-.*.scope" | head -n 1 | sed "s/docker-\(.*\).scope/\\1/"
  register: container_id

- name: Get Image name
  shell: docker inspect --format='{% raw %}{{.Config.Image}}{%endraw%}' "{{container_id.stdout}}" 
  register: container_image

- name: Create Undercloud data container
  docker_container:
    state: present
    recreate: true
    name: undercloud-volumes
    image: flaper87/tripleo-undercloud-init-container
    volumes:
        - /tmp:/tmp
        - /etc/hosts:/etc/hosts
        - /etc/puppet:/etc/puppet
        - /etc/ssh:/etc/ssh
        - /var/lib/kolla:/var/lib/kolla
        - /var/lib/docker-puppet:/var/lib/docker-puppet
        - /var/lib/config-data:/var/lib/config-data
        - /var/run:/var/run

- name: Deploy the undercloud
  docker_container:
    state: started 
    recreate: true
    name: undercloud-deploy
    detach: true
    user: root
    network_mode: host
    privileged: true
    entrypoint: /root/deploy.sh
    image: '{{container_image.stdout}}'
    volumes_from:
      - '{{container_id.stdout}}'
      - undercloud-volumes
